# Generated by Django 4.1.6 on 2023-02-04 06:49

from django.db import migrations, models
import validator.models


class Migration(migrations.Migration):

    dependencies = [
        ('validator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivosAlumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo_url', models.FileField(upload_to=validator.models.upload_to2)),
                ('codigocurso', models.CharField(max_length=10)),
                ('grupo', models.CharField(max_length=1)),
                ('docente', models.CharField(max_length=100)),
            ],
        ),
    ]
