# Generated by Django 4.1.6 on 2023-02-04 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigoalumno', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=100)),
                ('codigocurso', models.CharField(max_length=10)),
                ('grupo', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('presente', models.BooleanField(default=False)),
                ('observacion', models.TextField(blank=True)),
                ('idmatricula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asistencia.matricula')),
            ],
        ),
    ]
