# Generated by Django 4.1.6 on 2023-02-03 06:02

import curso.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('denominacion', models.CharField(max_length=100)),
                ('creditos', models.PositiveSmallIntegerField()),
                ('codigo', models.CharField(max_length=10)),
                ('grupo', models.CharField(max_length=1)),
                ('matriculados', models.PositiveSmallIntegerField()),
                ('carrera', models.CharField(max_length=100)),
                ('docente', models.CharField(max_length=100)),
                ('silabo_url', models.FileField(blank=True, default=None, null=True, upload_to=curso.models.upload_to)),
            ],
        ),
    ]
