# Generated by Django 4.1.6 on 2023-02-03 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(max_length=10)),
                ('hi', models.TimeField(blank=True, null=True)),
                ('hf', models.TimeField(blank=True, null=True)),
                ('aula', models.CharField(max_length=10)),
                ('codigo_curso', models.CharField(max_length=10)),
                ('grupo', models.CharField(max_length=1)),
                ('tipo', models.CharField(max_length=1)),
                ('carrera', models.CharField(max_length=100)),
                ('docente', models.CharField(max_length=100)),
            ],
        ),
    ]
