# Generated by Django 4.1.6 on 2023-02-03 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('horario', '0003_alter_horario_codigo_curso_alter_horario_dia'),
    ]

    operations = [
        migrations.RenameField(
            model_name='horario',
            old_name='codigo_curso',
            new_name='codigocurso',
        ),
    ]
